---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  strategy:   # стратегия деплоя, обновления
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1         # можно указать в процентах
      maxUnavailable: 1   # можно указать в процентах
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:1.20
        name: nginx
        ports:
        - containerPort: 80
...