apiVersion: apps/v1     # не базовый объект, основанный на другом базовом объекте (просто v1 - базовый объект)
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 2       # желаемое количество реплик поды, объявленной в template
  selector:         # данный replicaSet будет считать своими все поды с меткой my-app
    matchLabels:    
      app: my-app
  template:         # шаблон контейнеров, создаваемых этим replicaset
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:1.20
        name: nginx
        ports:
        - containerPort: 80
...